export const ACTION_USER_LOGIN = 'ACTION_USER_LOGIN';//事例
export const ACTION_USER_LOGOUT = 'ACTION_USER_LOGOUT';//事例
export const ACTION_CHECK_USER_LOGIN = 'ACTION_CHECK_USER_LOGIN';//事例
export const ACTION_USER_AVATER_CHANGE = 'ACTION_USER_AVATER_CHANGE';//事例
